# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
'''
zero 是所有元素都為0
empty是以0為起始值 後面元素值皆為隨機數
'''

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [23]:
# 記得先 Import 正確的套件
import numpy as np

In [31]:
# 參考解答

a = np.random.rand(2, 3)
b = np.round(a)
print(a)
print(b)


[[0.34092859 0.01427277 0.64837113]
 [0.10469249 0.44854947 0.58750474]]
[[0. 0. 1.]
 [0. 0. 1.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [47]:

m = 20
n = 40

b=np.random.randint(20,40,size=(2,3))
print(b)

[[29 32 35]
 [21 33 34]]


In [37]:
import numpy as np
from numpy.random import default_rng
m=20
n=40
b = default_rng()
integers = b.integers(m, n, size=(2,3))
print(integers)

[[25 39 35]
 [28 25 27]]


In [45]:
m = 20
n = 40

b=np.random.randint(20,40,size=(2,3))
print(b)

[[32 32 37]
 [27 26 34]]
